
const chatTypes = {
    GET_PATIENT_CHAT: "GET_PATIENT_CHAT",
    SET_CHAT_IN_PATIENT: "SET_CHAT_IN_PATIENT",
    ADD_CHAT_IN_PATIENT: "ADD_CHAT_IN_PATIENT",
    UPDATE_CHAT_IN_PATIENT: "UPDATE_CHAT_IN_PATIENT",
    REFRESH_CHAT_IN_PATIENT: "REFRESH_CHAT_IN_PATIENT",
    UPDATE_CHAT_IN_PATIENT_SUCCESS: "UPDATE_CHAT_IN_PATIENT_SUCCESS",

}


export default chatTypes