
const otherTypes = {
  IS_LOADING: "IS_LOADING",
  LOADING_MSG: "LOADING_MSG",
  UPLOAD_FILE: "UPLOAD_FILE",
  UPLOAD_FILE_ARRAY: "UPLOAD_FILE_ARRAY",
  CANCEL_UPLOAD: "CANCEL_UPLOAD",
  REFRESH_LANGUAGE: "REFRESH_LANGUAGE",
  RESET_STATE_ON_LOGIN: "RESET_STATE_ON_LOGIN",
  RESET_STATE_ON_LOGOUT: "RESET_STATE_ON_LOGOUT",
}


export default otherTypes