
const patientTypes = {
    FETCH_ALL_PATIENTS: "FETCH_ALL_PATIENTS",
    SET_ALL_PATIENTS: "SET_ALL_PATIENTS",
    INCREASE_UNREAD_MESSAGE: "INCREASE_UNREAD_MESSAGE",
    MARK_READ_MESSAGES: "MARK_READ_MESSAGES",
}

export default patientTypes