import AntDesign from "react-native-vector-icons/AntDesign";
import Ionicons from "react-native-vector-icons/Ionicons";
import MaterialCommunityIcons from "react-native-vector-icons/MaterialCommunityIcons";
import MaterialIcons from "react-native-vector-icons/MaterialIcons";
import { colors } from "./Colors";

export const Images = {
  ic_doctor_placeholder: MaterialCommunityIcons.getImageSourceSync('doctor', 100, colors.colorPrimary),
  ic_filter_icon: AntDesign.getImageSourceSync('filter', 50, colors.colorPrimary),
  ic_success_alert_icon: Ionicons.getImageSourceSync("ios-checkmark-circle-outline", 50, colors.colorWhite),
  ic_profile_placeholder: Ionicons.getImageSourceSync('person-circle', 100, colors.colorWhite),
  ic_arrow_down: MaterialIcons.getImageSourceSync('keyboard-arrow-down', 50, colors.colorBlackText),
  ic_plus_icon: AntDesign.getImageSourceSync('plus', 30, colors.colorPrimary),
  ic_plus_ion_icon: Ionicons.getImageSourceSync('add', 30, colors.colorBlack),
  ic_camera_icon: MaterialCommunityIcons.getImageSourceSync('camera', 30, colors.colorPrimary),
  ic_gallery_icon: MaterialIcons.getImageSourceSync('photo-library', 50, colors.colorPrimary),
  ic_file_icon: MaterialIcons.getImageSourceSync('picture-as-pdf', 30, colors.colorPrimary),
  ic_lock: MaterialIcons.getImageSourceSync('lock-outline', 30, colors.colorPrimary),
  ic_info: MaterialIcons.getImageSourceSync('info-outline', 30, colors.colorPrimary),
  ic_search: MaterialIcons.getImageSourceSync('search', 30, colors.colorPrimary),
  ic_get_started: require("./images/ic_get_started.png"),
  ic_translation: require("./images/ic_translate.png"),
  ic_eng: require("./images/ic_eng.png"),
  ic_thai: require("./images/ic_thai.png"),
  ic_phone: require("./images/ic_phone.png"),
  ic_otp: require("./images/ic_otp.png"),
  ic_passport: require("./images/ic_passport.png"),
  ic_id_card: require("./images/ic_id_card.png"),
  ic_upload: require("./images/ic_upload.png"),
  ic_home: require("./images/ic_home.png"),
  ic_home_focused: require("./images/ic_home_focused.png"),
  ic_records: require("./images/ic_records.png"),
  ic_records_focused: require("./images/ic_records_focused.png"),
  ic_account: require("./images/ic_account.png"),
  ic_account_focused: require("./images/ic_account_focused.png"),
  ic_covid_frame: require("./images/ic_covid_frame.png"),
  ic_stress_frame: require("./images/ic_stress_frame.png"),
  ic_doctors: require("./images/ic_doctors.png"),
  ic_nurse_chat: require("./images/ic_nurse_chat.png"),
  ic_line_chat: require("./images/ic_line_chat.png"),
  ic_support: require("./images/ic_support.png"),
  ic_consultation: require("./images/ic_consultation.png"),
  ic_doctor_sample: require("./images/ic_doctor_sample.png"),
  ic_app: require("./images/ic_app.png"),
  ic_camera: require("./images/ic_camera.png"),
  ic_account_info: require("./images/ic_account_info.png"),
  ic_family: require("./images/ic_family.png"),
  ic_medical_history: require("./images/ic_medical_history.png"),
  ic_address: require("./images/ic_address.png"),
  ic_payment: require("./images/ic_payment.png"),
  ic_document: require("./images/ic_document.png"),
  ic_insurance: require("./images/ic_insurance.png"),
  ic_help: require("./images/ic_help.png"),
  ic_logout: require("./images/ic_logout.png"),
  ic_the_doc: require("./images/ic_the_doc.png"),
  ic_calender: require("./images/ic_calender.png"),
  ic_video: require("./images/ic_video.png"),
  ic_symptoms: require("./images/ic_symptoms.png"),
  ic_diagnosis: require("./images/ic_diagnosis.png"),
  ic_pdf: require("./images/ic_pdf.png"),
  ic_complete: require("./images/ic_complete.png"),
  ic_birthday: require("./images/ic_birthday.png"),
  ic_attachment: require("./images/ic_attachment.png"),
  ic_warning: require("./images/ic_warning.png"),
  ic_insurance_back: require("./images/ic_insurance_back.png"),
  ic_insurance_front: require("./images/ic_insurance_front.png"),
  ic_chat_doc: require("./images/ic_chat_doc.png"),
  ic_chat: require("./images/ic_chat.png"),
  // ic_insurance_front: require("./images/ic_insurance_front.png"),
};
